#!/bin/zsh
#Alias
#Auto open files
alias -s {jpg,JPG,jpeg,JPEG,png,PNG,gif,GIF}='feh'
alias -s {mpg,mpeg,avi,ogm,ogv,wmv,m4v,mp4,mov,f4v,mkv}='mplayer'
alias -s {mp3,ogg,wav,flac}='ncmpcpp'
alias -s {html,php,com,net,org,gov}='chromium-browser'
alias -s pdf='zathura'
alias -s chm='xchm'
alias -s {rar,zip,7z,tar}='extract'
alias -s {txt}='v'

# The 'cd' family ------------
alias -g ~='cd ~'
alias -g ..='cd ..'
alias -g ...='cd ../..'
alias -g ....='cd ../../..'
alias -g .....='cd ../../../..'

# The git family
alias gs='git status'
alias gc='git commit'
alias ga='git add'
alias gp='git push'

# Command
alias s='sudo'
alias cp='cp -i -r'
alias mv='mv -i'
alias md='mkdir -p'
alias grep='grep --color=auto'
alias p='packer'
alias clean='sudo pacman -Rsn $(pacman -Qdtq)'
alias sd='shutdown -h now'
alias ws='sudo wifi-select wlan0'

#Quickly navigate fav folder
dataFolder='/mnt/data'
alias inbox='cd ${dataFolder}/inbox'
alias book='cd ${dataFolder}/Dropbox/book/'
alias dev='cd ${dataFolder}/dev'
alias build='cd ~/.build/'
alias cw='/srv/http/'

#Tweak application default running mode
alias scrot='scrot -q100'
alias urxvt='urxvtc&'
alias gimp='gimp&exit'
alias def="sdcv -u Oxford\ Advanced\ Learner\'s\ Dictionary"
alias asynonym="sdcv -u Moby\ Thesaurus\ II"
alias vifm='vifm .'

#Editor
alias v='vim'
